### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by parafoxia** [Jonxslays/piston_rspy#12]
## Summary

The following error appears when installing piston_rspy via pip (or uv):

```
Collecting piston_rspy
  Downloading piston_rspy-0.4.1.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
      /private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `license = 'MIT'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `authors` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `authors = 'Jonxslays'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `authors` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `authors` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `classifiers` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `classifiers = ['Development Status :: 3 - Alpha', 'Framework :: AsyncIO', 'License :: OSI Approved :: MIT License', 'Operating System :: OS Independent', 'Programming Language :: Rust', 'Programming Language :: Python :: 3 :: Only', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: 3.10', 'Programming Language :: Python :: 3.11', 'Programming Language :: Python :: Implementation :: CPython', 'Topic :: Software Development :: Libraries :: Python Modules', 'Typing :: Typed']`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `classifiers` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `classifiers` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `urls` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `urls = {'Documentation': 'https://jonxslays.github.io/piston_rspy/piston_rspy', 'Source': 'https://github.com/Jonxslays/piston_rspy', 'Bug Tracker': 'https://github.com/Jonxslays/piston_rspy/issues'}`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `urls` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `urls` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      Traceback (most recent call last):
        File "/Users/ethanhenderson/Programs/Carberra/Tutorials/Perfect/astral-uv/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ethanhenderson/Programs/Carberra/Tutorials/Perfect/astral-uv/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/ethanhenderson/Programs/Carberra/Tutorials/Perfect/astral-uv/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
          return _apply(dist, config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 57, in apply
          _apply_project_table(dist, config, root_dir)
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 83, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/private/var/folders/1_/bnl0lhl55cg5mtp5xcqm0dg40000gn/T/pip-build-env-2qi4n2rw/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 184, in _license
          _set_config(dist, "license", val["text"])
                                       ~~~^^^^^^^^
      KeyError: 'text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Environment

* Python 3.11.7
* piston_rspy 0.4.1
* pip 23.3.1

**Comment by Jonxslays** [comment]
Thanks for the report, I will investigate this weekend.

**Comment by Jonxslays** [comment]
@parafoxia I wasn't able to reproduce your error on my system. I can see in your output it was attempting to build from source. I updated the build CI, care to give it another go?

**Comment by parafoxia** [comment]
Yeah seems to be working now!
